[menu]
executable = 'rofi'
args = [
    '-dmenu',
    '-i',
    '-cache-dir "/dev/null"',
    '-p {prompt}',
    '-markup-rows',
]

[format]
window_format = "<i>{app_name}</i> - <b>“{title}“</b> on workspace {workspace_name} / {output_name}\u0000icon\u001f{app_icon}"
